alias: beok_align_currenttemp
description: ""
triggers:
  - platform: state
    entity_id: sensor.desk_temperature
    for: "00:00:05"
  - platform: state
    entity_id: climate.beok_thermostat
    attribute: current_temperature
    for: "00:00:05"
conditions:
  - condition: template
    value_template: >-
      {{ (states('sensor.desk_temperature') | float -
      (state_attr('climate.beok_thermostat','current_temperature') | float) ) |
      abs > 0.1 }}
actions:
  - target:
      entity_id: input_number.beok_offset
    data:
      value: >-
        {{ ((states('number.beok_thermostat_local_temperature_calibration') |
        float) + (states('sensor.desk_temperature') | float) -
        (state_attr('climate.beok_thermostat','current_temperature') | float)) |
        round(1) }}
    action: input_number.set_value
  - wait_template: "{{ false }}"
    timeout: "00:00:02"
  - action: number.set_value
    metadata: {}
    target:
      entity_id: number.beok_thermostat_local_temperature_calibration
    data:
      value: "{{ states('input_number.beok_offset') | float | round(1) }}"
mode: single
