esphome:
  name: espfan
  friendly_name: ESP Fan

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf


# Substitutions for easy configuration
substitutions:
  temp_min: "30.0"  # Temperature at which fan starts (0% speed)
  temp_max: "45.0"  # Temperature at which fan reaches 100% speed
  temp_hysteresis: "2.0"  # Temperature hysteresis to prevent rapid cycling
  rpm_multiplier: "0.5"  # RPM calculation multiplier (typically 0.5 for 2 pulses/rev)
  fan_min_power: "0.20"  # Minimum PWM power (20%) - prevents fan buzzing at low speeds

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_pw

# Antenna problem: no stable wifi with the onboard antenna. what worked for me 
# is a 31mm piece of wire connected to the "0" side of the onboard antenna (no loop to the other side!)
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # output_power: 20.0 dBm
  # power_save_mode: none  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espfan Fallback Hotspot"
    password: !secret hotspot_pw

captive_portal:

# Web server (optional, for debugging)
web_server:
  port: 80


# GPIO output for MOSFET power switch (enable/disable fans completely)
# WARNING: GPIO0 is a strapping pin on ESP32-C3. It is held LOW during boot to enter bootloader.
# The 10kÎ© pullup resistor in the MOSFET circuit prevents boot issues, but fans may briefly
# power on during ESP32 boot/reset until the GPIO is properly initialized.
output:
  - platform: gpio
    pin: GPIO0
    id: fan_power_enable
    inverted: false

  - platform: ledc
    pin: GPIO1
    id: fan_pwm
    frequency: 25000 Hz
    min_power: ${fan_min_power}  # Minimum 20% - fan won't spin below this
    max_power: 1.0
    zero_means_zero: true  # Ensure 0% truly turns output off

# Fan control with speed and power enable
fan:
  - platform: speed
    output: fan_pwm
    name: "Fan"
    id: fan_control
    on_turn_on:
      - output.turn_on: fan_power_enable
    on_turn_off:
      - output.turn_off: fan_power_enable

# DHT22 Temperature and Humidity Sensor
# NOTE: GPIO2 is a strapping pin on ESP32-C3, but safe to use for DHT22 after boot
sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Temperature"
      id: temperature
      on_value:
        then:
          - if:
              condition:
                switch.is_on: auto_mode
              then:
                - lambda: |-
                    float temp = id(temperature).state;
                    float speed = 0.0;
                    float temp_min = ${temp_min};
                    float temp_max = ${temp_max};
                    float hysteresis = ${temp_hysteresis};
                    
                    // Apply hysteresis based on current fan state
                    bool fan_is_on = id(fan_control).state;
                    float effective_min = fan_is_on ? temp_min - hysteresis : temp_min;
                    
                    if (temp >= temp_max) {
                      speed = 1.0;  // 100% at temp_max and above
                    } else if (temp > effective_min) {
                      // Linear interpolation between temp_min (0%) and temp_max (100%)
                      speed = (temp - temp_min) / (temp_max - temp_min);
                      speed = max(0.0f, min(1.0f, speed));  // Clamp to 0-1 range
                    } else {
                      speed = 0.0;  // 0% at temp_min and below
                    }
                    
                    if (speed > 0.0) {
                      auto call = id(fan_control).turn_on();
                      call.set_speed(static_cast<int>(speed * 100));
                      call.perform();
                    } else {
                      id(fan_control).turn_off().perform();
                    }
    humidity:
      name: "Humidity"
      id: humidity
    update_interval: 10s

  - platform: pulse_counter
    pin: 
      number: GPIO3
      mode:
        input: true
        pullup: true
    name: "Fan 1 RPM"
    id: fan1_rpm
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    update_interval: 5s
    filters:
      - multiply: ${rpm_multiplier}  # Adjust based on your fan's pulses per revolution
    
  - platform: pulse_counter
    pin: 
      number: GPIO4
      mode:
        input: true
        pullup: true
    name: "Fan 2 RPM"
    id: fan2_rpm
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    update_interval: 5s
    filters:
      - multiply: ${rpm_multiplier}  # Adjust based on your fan's pulses per revolution

# Mode selection switch (Auto/Manual)
switch:
  - platform: template
    name: "Auto Mode"
    id: auto_mode
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "Switched to Auto Mode - Temperature controlled"
    on_turn_off:
      - logger.log: "Switched to Manual Mode"
