# minimal configuration - manual mode only, no temperature control (for testing/development)
esphome:
  name: espfan
  friendly_name: ESP Fan

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Substitutions for easy configuration
substitutions:
  temp_min: "30.0"  # Temperature at which fan starts (0% speed)
  temp_max: "45.0"  # Temperature at which fan reaches 100% speed
  temp_hysteresis: "2.0"  # Temperature hysteresis to prevent rapid cycling
  rpm_multiplier: "0.5"  # RPM calculation multiplier (typically 0.5 for 2 pulses/rev)
  fan_min_power: "0.2"  # Minimum PWM power (20%) - prevents fan buzzing at low speeds

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espfan Fallback Hotspot"
    password: !secret hotspot_pw

captive_portal:

# Web server (optional, for debugging)
web_server:
  port: 80

# PWM output for fan speed control
output:
  - platform: ledc
    pin: GPIO25
    id: fan_pwm
    frequency: 25000 Hz
    min_power: ${fan_min_power}  # Minimum 20% - fan won't spin below this
    max_power: 1.0
    zero_means_zero: true  # Ensure 0% truly turns output off

# Fan control with speed
fan:
  - platform: speed
    output: fan_pwm
    name: "Fan"
    id: fan_control

# DHT22 Temperature and Humidity Sensor
sensor:
  - platform: pulse_counter
    pin: 
      number: GPIO26
      mode:
        input: true
        pullup: true
    name: "Fan 1 RPM"
    id: fan1_rpm
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    update_interval: 5s
    filters:
      - multiply: ${rpm_multiplier}  # Adjust based on your fan's pulses per revolution
    
  - platform: pulse_counter
    pin: 
      number: GPIO27
      mode:
        input: true
        pullup: true
    name: "Fan 2 RPM"
    id: fan2_rpm
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    update_interval: 5s
    filters:
      - multiply: ${rpm_multiplier}  # Adjust based on your fan's pulses per revolution

# Mode selection switch (Auto/Manual)
switch:
  - platform: template
    name: "Auto Mode"
    id: auto_mode
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "Switched to Auto Mode - Temperature controlled"
    on_turn_off:
      - logger.log: "Switched to Manual Mode"
